INSERT INTO category (name, times, notes) VALUES ('Debt', 0, 'Use it when you need to account for carry-over from the previous months, make adjustements to the balance etc.');
INSERT INTO category (name, times, notes) VALUES ('Food', 0, 'Says it all');
INSERT INTO category (name, times, notes) VALUES ('Gifts', 0, '');
INSERT INTO category (name, times, notes) VALUES ('Health', 0, '');
INSERT INTO category (name, times, notes) VALUES ('Coffee', 0, '');
INSERT INTO category (name, times, notes) VALUES ('Gas', 0, '');
INSERT INTO category (name, times, notes) VALUES ('Personal', 0, '');
INSERT INTO category (name, times, notes) VALUES ('Pets', 0, '');
INSERT INTO category (name, times, notes) VALUES ('Utilities', 0, '');
INSERT INTO category (name, times, notes) VALUES ('Travel', 0, '');
INSERT INTO category (name, times, notes) VALUES ('Other', 0, '');
INSERT INTO category (name, times, notes) VALUES ('Cigarettes', 0, '');
INSERT INTO category (name, times, notes) VALUES ('Pool', 0, '');
INSERT INTO category (name, times, notes) VALUES ('Car maintenance', 0, '');
